# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # It may not work for you. I am on an arm64 cluster, and the image is arm64.
  repository: ghcr.io/gargakshit/zerodha-task-app
  pullPolicy: Always
  tag: latest # Remove this to sync it with the app version in Chart.yml

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: app.k8s.orb.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

env:
  - name: DEMO_REDIS_ADDR
    value: "redis-headless.demo-ops.svc.cluster.local:6379"
  - name: DEMO_APP_ADDR
    value: "0.0.0.0:8080"
